title: My Blog
email: yangchenghaiyyds@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about coding, fitness, and study life.
baseurl: ""
url: "http://127.0.0.1:4000"
author: Yang Chenghai
avatar: /logo.png
theme: jekyll-theme-hamilton

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: yang88480430
github_username:  yangchenghai0430
logo: logo.png
social:
  name: Shangzhi Huang
  links:
    - https://x.com/yang88480430
    - https://github.com/yangchenghai0430?tab=repositories
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
